version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: lapkovskyk/nest-test
    container_name: nodejs
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    networks:
      - app-network
    command: npm run start
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=profile
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
